#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from common import *

NODE = "node8"

for b in BROKERS:
  host, port, user, pw = BRADDRS[b]
  conn = Connection(auth=True)
  conn.tracing("frm")
  print "Trying send: %s%s" % (b, BRADDRS[b])
  conn.connect(host=host, port=port)
  conn.open(mechanism="PLAIN", username=user, password=pw)
  ssn = conn.session()
  snd = ssn.sender(NODE)
  snd.send(Message(content="test"), settled=True)
  snd.close()
  ssn.close()
  conn.close()

  conn = Connection(auth=True)
  conn.tracing("frm")
  print "Trying recv: %s%s" % (b, BRADDRS[b])
  conn.connect(host=host, port=port)
  conn.open(mechanism="PLAIN", username=user, password=pw)
  ssn = conn.session()
  rcv = ssn.receiver(NODE, limit=1)
  while rcv.pending(block=True):
    msg = rcv.get()
    print b, msg
    rcv.disposition(msg.delivery_tag, ACCEPTED)
  settle(rcv)
  rcv.close()
  ssn.close()
  conn.close()
